[tox]
envlist=py{312,313,314}
skip_missing_interpreters=True

[testenv]
deps=-rrequirements-dev-3.txt
commands=
    python -m unittest discover -s tests {posargs}
allowlist_externals=make

[testenv:dev]
deps=-rrequirements-dev.txt
usedevelop=True
